---
# tasks file for osp_keypair
- name: Generate key files
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/test_id_rsa

- name: Ensure Keyair is present
  os_keypair:
    name: keypair1
    state: present
    cloud: ospcloud
    public_key_file: "{{Â ansible_env.HOME }}/.ssh/test_id_rsa.pub"
